### ISSUE TITLE
Adicionar verificação

### ISSUE THREAD

**Issue by fabriciopereiradiniz** [fabriciopereiradiniz/CAJ#1]
Necessário adição de verificação antes do professor adicionar nova nota, pra não ser > que 10 já que ela tem double precision

pseudocodigo
if nota_nova > 10{

} else nota = nota_nova;

- [x] Adição realizada.

**Comment by fabriciopereiradiniz** [comment]
![image](https://github.com/fabriciopereiradiniz/trabGuerino/assets/128907608/052cca78-64f3-4104-b5cf-d0af16921305)
/\ impossibilitar isto

**Comment by TardivoJP** [comment]
Coloquei lá bem basicao e utilizei o popup criado ali. Você precisa alterar agora para ter um "X" de saída.

![caputre13](https://github.com/fabriciopereiradiniz/CAJ/assets/88660138/8bea8fb6-18e8-4025-8fa2-c17926ec276e)
