### ISSUE TITLE
BUG Nota menor que 10

### ISSUE THREAD

**Issue by fabriciopereiradiniz** [fabriciopereiradiniz/CAJ#2]
A verificação da nota ter de ser menor que 10 tá bugada, esperar eu subir a atualização pra arrumar isso
![image](https://github.com/fabriciopereiradiniz/CAJ/assets/128907608/9441c676-2e45-4906-b132-d3232ce5d41a)

**Comment by TardivoJP** [comment]
O código está funcionando corretamente, a mensagem que estava errada, o correto é de 0 a 10, agora está modificado com o commit [8914c7d0fd343f5d224328af2ad179cbd932243d](https://github.com/fabriciopereiradiniz/CAJ/commit/8914c7d0fd343f5d224328af2ad179cbd932243d)
